/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sign */

#ifndef _Included_Sign
#define _Included_Sign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sign
 * Method:    getSign0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Sign_getSign0
  (JNIEnv *, jclass, jstring, jstring, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
