name: noise-watermark
channels:
- pytorch
- defaults
dependencies:
- jupyter
- nb_conda
- numpy
- pyyaml
- mkl
- setuptools
- cmake
- cffi
- pytorch=0.4
- cpuonly
- matplotlib
- scikit-image
- torchvision
- opencv
